### ISSUE TITLE
What to include in the boilerplate

### ISSUE THREAD

**Issue by bertearazvan** [DHI-GRAS/gras-react-boilerplate#1]
The boilerplate should include
- [x] Map - using `react-map-gl` and not `react-mapbox-gl`
- [x] Sidebar
- [x] Sidebar control
- [x] Navbar
- [x] ~~Bottom drawer~~

~~Would be nice to include maybe some template for routing using `react-router`?~~
I also believe it would be nice to build it and then recreate the components inside the `@dhi-gras/react-components`.
Should the components be made in `tsx` or `jsx`?

The way I see it is that we could make the boilerplate with all the mentioned components bound together and then make it easier for the developer to remove what it's not needed.
@Robert-OP @JeroenDerks

**Comment by JeroenDerks** [comment]
I think we can neglect the bottom drawer for now., and if you can find a way to add an optional Navbar, that would be great (we struggled with this layout before)

Map should indeed be `react-map-gl`
Sidebar can be empty or you can add your title component
Sidebar control should toggle the sidebar, and allow for icons to be inserted in its vertical center

I wouldnt worry about `react-router` yet.
You can decide on `tsx` vs `jsx` as youre more invested in the subject :)

**Comment by bertearazvan** [comment]
In regards to the `tsx` vs `jsx` the best practice is to use `tsx`.

An important factor to keep in mind is what the frontend developers that will use the boilerplate are comfortable coding in and if they are willing to learn `tsx`.

**Comment by Robert-OP** [comment]
@bertearazvan >> go for `.tsx` and include `react-map-gl` for now

**Comment by Robert-OP** [comment]
thought about it now to include environment variables

**Comment by bertearazvan** [comment]
![27e00219be365f11723de4693bd5c4f3](https://user-images.githubusercontent.com/30385700/91868008-8e8a2100-ec74-11ea-97ea-03000e68708f.png)

First draft @Robert-OP @JeroenDerks
